using '../main.bicep'

param environmentType = 'nonprod'
param postgreSQLServerName = 'aguadamillas-dbsrv-dev'
param postgreSQLDatabaseName = 'aguadamillas-db-dev'
param appServicePlanName = 'aguadamillas-asp-dev'
param appServiceAPIAppName = 'aguadamillas-be-dev'
param appServiceAppName = 'aguadamillas-fe-dev'
param location = 'North Europe'
param appServiceAPIDBHostFLASK_APP =  'iebank_api\\__init__.py'
param appServiceAPIDBHostFLASK_DEBUG =  '1'
param appServiceAPIDBHostDBUSER = 'github-secret-replaced-in-workflow'
param appServiceAPIEnvVarDBPASS =  'github-secret-replaced-in-workflow'
param appServiceAPIEnvVarDBHOST =  'aguadamillas-dbsrv-dev.postgres.database.azure.com'
param appServiceAPIEnvVarDBNAME =  'aguadamillas-db-dev'
param appServiceAPIEnvVarENV =  'dev'
