name: Key Vault Testing

on:
  workflow_dispatch:
  push:
    paths:
        - './modules/key-vault.bicep/**'
        - './parameters/kv-test.json/**'
#   pull_request:
#     branches: [ "main" ]

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-A-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-A-UAT
  RESOURCE_GROUP_PROD: BCSAI2024-DEVOPS-STUDENTS-A-PROD

jobs:
  build:
    name: Build and Lint Key Vault Bicep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Bicep Linter
        run: |
          az bicep build --file ./modules/key-vault.bicep

  test-keyvault:
    name: Validate and Dry Run Key Vault
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Dry Run Key Vault Deployment
        run: |
            az deployment group what-if \
              --resource-group ${{ env.RESOURCE_GROUP_DEV }} \
              --template-file ./modules/key-vault.bicep \
              --parameters @parameters/kv-test.json

  deploy-keyvault:
    name: Deploy Key Vault
    runs-on: ubuntu-latest
    needs: test-keyvault
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2   
    
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Test Key Vault
        run: |
            az deployment group create \
              --resource-group ${{ env.RESOURCE_GROUP_DEV }} \
              --template-file ./modules/key-vault.bicep \
              --parameters @parameters/kv-test.json 




